headersOrigin = "config"
redirectsOrigin = "config"

[functions]

[functions."*"]

[[plugins]]
origin = "config"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[build]
publish = "/home/administrador/bitcoinbrasil/.next"
publishOrigin = "config"
commandOrigin = "config"
command = "npm install --legacy-peer-deps && npm run build"

[build.environment]
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
from = "/yuotube"
to = "https://yuotube.ai"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/youtube"
to = "https://yuotube.ai"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/standardbitcoin"
to = "https://standardbitcoin.io"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/bitcoin"
to = "https://standardbitcoin.io"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/stbtcx"
to = "https://pump.fun"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]